CREATE DATABASE IF NOT EXISTS buffering;

USE buffering;

CREATE TABLE IF NOT EXISTS user(
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(15) NOT NULL UNIQUE,
    password CHAR(128),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    roleId INT NOT NULL,
        CONSTRAINT fk_role
        FOREIGN KEY (roleId)
        REFERENCES role(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS role(
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(25) NOT NULL UNIQUE,
    description VARCHAR(255)
) ENGINE=INNODB;
